model_conf:
  detector:
    model_name: yolov8n.pt
    num_classes: 1
    pretrained: true

  ocr:
    img_height: 32
    img_width: 200
    hidden_size: 256
    num_layers: 2
    dropout: 0.3
    english_only: true
